prfeng@ubuntu:~/qca-networking-2017-spf-5-0_qca_oem.git/qsdk$ make 
 make[1] world
 make[2] target/compile
 make[3] -C target/linux compile
 make[2] package/cleanup
 make[2] package/compile
 make[3] -C package/libs/toolchain compile
 make[3] -C package/libs/libnl-tiny compile
 make[3] -C package/libs/libjson-c compile
 make[3] -C package/utils/lua compile
 make[3] -C package/libs/libubox compile
 make[3] -C package/system/ubus compile
 make[3] -C package/system/uci compile
 make[3] -C package/network/config/netifd compile
 make[3] -C package/system/opkg host-compile
 make[3] -C package/system/ubox compile
 make[3] -C package/libs/gettext compile
 make[3] -C package/libs/libiconv compile
 make[3] -C package/libs/libtool compile
 make[3] -C package/libs/lzo compile
 make[3] -C package/libs/zlib compile
 make[3] -C package/libs/ncurses host-compile
 make[3] -C package/libs/ncurses compile
 make[3] -C package/libs/ncurses compile
 make[3] -C package/utils/util-linux compile
 make[3] -C package/utils/ubi-utils compile
 make[3] -C package/system/procd compile
 make[3] -C package/system/usign host-compile
 make[3] -C package/utils/jsonfilter compile
 make[3] -C package/system/usign compile
 make[3] -C package/base-files compile
 make[3] -C package/boot/lk-qca compile
 make[3] -C package/boot/lk-qca compile
 make[3] -C package/system/fstools compile
 make[3] -C package/boot/uboot-envtools compile
 make[3] -C package/boot/uboot-ipq40xx compile
 make[3] -C package/boot/uboot-ipq806x compile
 make[3] -C qca/feeds/qca_10_4/net/qca-wifi-fw-10.2.4 compile
 make[3] -C qca/feeds/qca_10_4/net/qca-wifi-fw-10.2.4 compile
 make[3] -C qca/feeds/qca_10_4/net/qca-wifi-fw-10.4-ar71xx compile
 make[3] -C qca/feeds/qca_10_4/net/qca-wifi-fw-10.4 compile
 make[3] -C qca/feeds/qca_10_4/net/qca-wifi-fw-10.4 compile
 make[3] -C qca/feeds/qca_10_4/net/qca-wifi-fw-10.4 compile
 make[3] -C package/firmware/linux-firmware compile
 make[3] -C package/kernel/linux compile
 make[3] -C package/network/utils/iproute2 compile
 make[3] -C package/network/utils/wireless-tools compile
 make[3] -C qca/feeds/nss-host/qca-nss-gmac compile
 make[3] -C qca/feeds/nss-host/qca-nss-drv compile
 make[3] -C qca/feeds/qca_10_4/net/qca-wifi-10.4 compile
 make[3] -C package/charlietalk compile
 make[3] -C package/charlietalk compile
 make[3] -C package/devel/binutils compile
 make[3] -C package/libs/libreadline compile
 make[3] -C package/devel/gdb compile
 make[3] -C package/devel/trace-cmd compile
 make[3] -C qca/feeds/athdiag/athdiag compile
 make[3] -C qca/feeds/bluetopia/bluetopia compile
 make[3] -C qca/feeds/qca-lib/libqcacommon compile
 make[3] -C qca/feeds/ieee1905-security/qca-ieee1905-security-config/libieee1905 compile
 make[3] -C qca/feeds/ieee1905-security/qca-ieee1905-security-config/libstorage compile
 make[3] -C qca/feeds/ieee1905-security/qca-ieee1905-security-config/libwpa2 compile
 make[3] -C qca/feeds/ieee1905-security/qca-ieee1905-security-config/qca-ieee1905-init compile
 make[3] -C qca/feeds/ieee1905-security/qca-ieee1905-security-config/qca-wsplcd compile
 make[3] -C qca/feeds/luci/modules/luci-base host-compile
 make[3] -C package/network/utils/iptables compile
 make[3] -C package/network/config/firewall compile
 make[3] -C package/utils/lua host-compile
 make[3] -C qca/feeds/luci/applications/luci-app-firewall compile
 make[3] -C qca/feeds/luci/libs/luci-lib-ip compile
 make[3] -C qca/feeds/luci/libs/luci-lib-nixio compile
 make[3] -C package/network/utils/iwinfo compile
 make[3] -C package/system/rpcd compile
 make[3] -C qca/feeds/luci/modules/luci-base compile
 make[3] -C qca/feeds/luci/modules/luci-mod-admin-full compile
 make[3] -C qca/feeds/luci/protocols/luci-proto-ppp compile
 make[3] -C qca/feeds/luci/themes/luci-theme-bootstrap compile
 make[3] -C package/libs/polarssl compile
 make[3] -C package/libs/ustream-ssl compile
 make[3] -C package/network/services/uhttpd compile
 make[3] -C qca/feeds/luci/protocols/luci-proto-ipv6 compile
 make[3] -C qca/feeds/luci/collections/luci compile
 make[3] -C package/libs/ocf-crypto-headers compile
 make[3] -C package/libs/openssl compile
 make[3] -C qca/feeds/packages/net/bind compile
 make[3] -C qca/feeds/packages/net/ddns-scripts compile
 make[3] -C qca/feeds/luci/applications/luci-app-ddns compile
 make[3] -C qca/feeds/packages/net/multiwan compile
 make[3] -C qca/feeds/luci/applications/luci-app-multiwan compile
 make[3] -C package/network/services/samba36 compile
 make[3] -C qca/feeds/luci/applications/luci-app-samba compile
 make[3] -C qca/feeds/routing/miniupnpd compile
 make[3] -C qca/feeds/luci/applications/luci-app-upnp compile
 make[3] -C qca/feeds/nss-host/qca-rfs compile
 make[3] -C qca/feeds/ssdk/qca-ssdk compile
 make[3] -C qca/feeds/networking/lacpd compile
 make[3] -C package/libs/gmp compile
 make[3] -C qca/feeds/networking/openswan compile
 make[3] -C qca/feeds/networking/rstp compile
 make[3] -C qca/feeds/nss-host/qca-edma compile
 make[3] -C qca/feeds/nss-host/qca-nss-crypto compile
 make[3] -C qca/feeds/nss-host/qca-nss-cfi compile
 make[3] -C package/network/ipv6/map compile
 make[3] -C qca/feeds/routing/nat46 compile
 make[3] -C qca/feeds/nss-host/qca-nss-clients compile
 make[3] -C qca/feeds/qca-mcs/qca-mcs-lkm compile
 make[3] -C qca/feeds/shortcut-fe/shortcut-fe compile
 make[3] -C qca/feeds/shortcut-fe/simulated-driver compile
 make[3] -C qca/feeds/nss-host/qca-nss-ecm compile
 make[3] -C qca/feeds/nss-host/qca-nss-macsec compile
 make[3] -C qca/feeds/packages/libs/alsa-lib compile
 make[3] -C qca/feeds/packages/utils/alsa-utils compile
 make[3] -C qca/feeds/packages/net/bridge-utils compile
 make[3] -C qca/feeds/packages/utils/attr compile
 make[3] -C qca/feeds/packages/utils/acl compile
 make[3] -C qca/feeds/packages/utils/coreutils compile
 make[3] -C qca/feeds/packages/utils/dosfstools compile
 make[3] -C qca/feeds/packages/net/ethtool compile
 make[3] -C qca/feeds/packages/libs/opus compile
 make[3] -C qca/feeds/packages/libs/speex compile
 make[3] -C package/utils/bzip2 compile
 make[3] -C qca/feeds/packages/multimedia/ffmpeg compile
 make[3] -C qca/feeds/packages/libs/file compile
 make[3] -C qca/feeds/packages/libs/libxml2 compile
 make[3] -C package/libs/uclibc++ compile
 make[3] -C qca/feeds/packages/libs/db47 compile
 make[3] -C qca/feeds/packages/libs/gdbm compile
 make[3] -C qca/feeds/packages/libs/libffi compile
 make[3] -C qca/feeds/packages/libs/expat host-compile
 make[3] -C qca/feeds/packages/libs/libffi host-compile
 make[3] -C package/utils/bzip2 host-compile
 make[3] -C qca/feeds/packages/lang/python host-compile
 make[3] -C qca/feeds/packages/libs/sqlite3 compile
 make[3] -C qca/feeds/packages/lang/python compile
 make[3] -C qca/feeds/packages/utils/i2c-tools compile
 make[3] -C qca/feeds/packages/utils/iozone compile
 make[3] -C qca/feeds/packages/net/isc-dhcp compile
 make[3] -C qca/feeds/packages/net/isc-dhcp compile
 make[3] -C qca/feeds/packages/libs/jansson compile
 make[3] -C qca/feeds/packages/libs/libgpg-error compile
 make[3] -C qca/feeds/packages/libs/libgcrypt compile
 make[3] -C qca/feeds/packages/libs/libmad compile
 make[3] -C qca/feeds/packages/libs/libogg compile
 make[3] -C qca/feeds/packages/libs/libvorbis compile
 make[3] -C qca/feeds/packages/libs/libtheora compile
 make[3] -C qca/feeds/packages/utils/minicom compile
 make[3] -C qca/feeds/packages/libs/opencore-amr compile
 make[3] -C qca/feeds/packages/multimedia/mplayer compile
 make[3] -C qca/feeds/packages/utils/ntfs-3g compile
 make[3] -C qca/feeds/packages/net/p910nd compile
 make[3] -C qca/feeds/packages/lang/perl host-compile
 make[3] -C qca/feeds/packages/lang/perl compile
 make[3] -C qca/feeds/packages/net/remserial compile
 make[3] -C package/libs/argp-standalone compile
 make[3] -C qca/feeds/packages/utils/rng-tools compile
 make[3] -C package/libs/libpcap compile
 make[3] -C package/network/utils/linux-atm compile
 make[3] -C package/network/utils/resolveip compile
 make[3] -C package/network/services/ppp compile
 make[3] -C qca/feeds/packages/net/rp-pppoe compile
 make[3] -C qca/feeds/packages/utils/shadow compile
 make[3] -C qca/feeds/packages/utils/sysstat compile
 make[3] -C qca/feeds/packages/net/xl2tpd compile
 make[3] -C qca/feeds/qca_10_4/utils/btdiag compile
 make[3] -C qca/feeds/qca_10_4/net/qca-acfg-10.4 compile
 make[3] -C package/libs/libnl compile
 make[3] -C qca/feeds/qca_10_4/net/qca-hostap-10.4 compile
 make[3] -C qca/feeds/qca_10_4/net/qca-hostap-10.4 compile
 make[3] -C qca/feeds/qca_10_4/net/qca-hostap-10.4 compile
 make[3] -C qca/feeds/qca_10_4/net/qca-iface-mgr-10.4 compile
 make[3] -C qca/feeds/qca_10_4/net/qca-lowi compile
 make[3] -C qca/feeds/qca_10_4/utils/qca-spectral-10.4 compile
 make[3] -C qca/feeds/qca_10_4/utils/qca-thermald-10.4 compile
 make[3] -C qca/feeds/qca_10_4/net/qca-wpc-10.4 compile
 make[3] -C qca/feeds/qca_10_4/net/qca-wrapd-10.4 compile
 make[3] -C qca/feeds/qca_10_4/utils/qcmbr-10.4 compile
 make[3] -C qca/feeds/qca-mcs/qca-mcs-apps compile
 make[3] -C qca/feeds/routing/mcproxy compile
 make[3] -C qca/feeds/routing/quagga compile
 make[3] -C qca/feeds/ssdk/qca-ssdk-shell compile
 make[3] -C qca/feeds/whc/qca-whc-init compile
 make[3] -C qca/feeds/whc/qca-whc-lbd compile
 make[3] -C qca/feeds/whc/qca-whc-luci compile
 make[3] -C qca/feeds/whc/qca-whc-repacd compile
 make[3] -C qca/feeds/whc/whc compile
 make[3] -C package/firmware/ath10k-firmware compile
 make[3] -C package/network/services/hostapd compile
 make[3] -C package/network/utils/iw compile
 make[3] -C qca/feeds/wlan-open/mac80211 compile
 make[3] -C package/hik/httpd compile
 make[3] -C package/kernel/button-hotplug compile
 make[3] -C package/kernel/gpio-button-hotplug compile
 make[3] -C package/libs/elfutils compile
 make[3] -C package/libs/libevent2 compile
 make[3] -C package/libs/librpc compile
 make[3] -C package/network/config/swconfig compile
 make[3] -C package/network/ipv6/6rd compile
 make[3] -C package/network/ipv6/ds-lite compile
 make[3] -C package/network/ipv6/odhcp6c compile
 make[3] -C package/network/services/dnsmasq compile
 make[3] -C package/network/services/dropbear compile
 make[3] -C package/network/services/lldpd compile
 make[3] -C package/network/services/odhcpd compile
 make[3] -C package/network/utils/arptables compile
 make[3] -C package/network/utils/iperf compile
 make[3] -C package/libs/sysfsutils compile
 make[3] -C package/network/utils/iputils compile
 make[3] -C package/network/utils/tcpdump compile
 make[3] -C package/network/utils/xtables-addons compile
 make[3] -C package/system/mtd compile
 make[3] -C package/system/opkg compile
 make[3] -C package/utils/alsa compile
 make[3] -C package/utils/busybox compile
 make[3] -C package/utils/e2fsprogs compile
 make[3] -C package/utils/lrzsz compile
 make[3] -C package/utils/mdadm compile
 make[3] -C package/utils/pm-utils compile
 make[2] package/install
 make[3] package/preconfig
 make[2] target/install
 make[3] -C target/linux install
 make[2] package/index