var iol=iol||{};iol.iolcookcs={};iol.dmp2={};iol.track={};iol.iolcookcs.ready=function(a){if("complete"==document.readyState)return a();window.addEventListener?window.addEventListener("load",a,!1):window.attachEvent?window.attachEvent("onload",a):window.onload=a};
iol.iolcookcs.ready(function(){(function(a){if(a.cookieChoices)return a.iol.cookieChoices;var b=a.document,d="textContent"in b.body,c=function(){function c(a){try{var l=b.createElement("img");l.src=("https:"==b.location.protocol?"https:":"http:")+"//adimg.virgilio.it/tracks/bi/images/bi_clk.gif?pmk="+a+"&rand="+Math.floor(1E7*Math.random()+1);l.width=1;l.height=1;var e=b.createDocumentFragment();e.appendChild(l);b.body.appendChild(e.cloneNode(!0))}catch(d){}}function k(a,b,e){d?a.textContent=b:a.innerText=
b;a.style.cssText=e}function p(a,l){var e=b.createElement("span");k(e,a,l);return e}function m(a,l,e){var c=b.createElement("a");k(c,l);c.id=a;c.href="#";c.style.cssText=e;return c}function h(a,l,e,c){var d=b.createElement("a");k(d,l);d.id=a;d.href=e;d.style.cssText=c;return d}function q(a,b,e){if(!a)return!1;if(a.addEventListener)return a.addEventListener(b,e,!0),!0;if(a.attachEvent)return a.attachEvent("on"+b,e)}function r(a,b,e){if(!a)return!1;if(a.addEventListener)return a.removeEventListener(b,
e),!0;if(a.attachEvent)return a.detachEvent("on"+b,e)}function f(a){try{0<b.location.href.indexOf("log=true")&&console.log(a)}catch(c){}}function y(){c("optin_leggi");return!0}function z(){return t("optin_ok")}function A(){return t("optin_close")}function t(a){try{f("_dismissLinkClick "+a);c(a);var d=B+"?value=1&r="+Math.floor(10*Math.random()+1),e=b.createElement("IFRAME");e.setAttribute("src",d);e.style.width="0px";e.style.height="0px";e.style.display="none";b.body.appendChild(e);f("createPolicyCookie created");
w();f("_dismissLinkClick  END "+a)}catch(n){}return!1}function C(c){try{null!=b.getElementById("cookieChoiceInfo")?(f("register Scroll"),t("optin_Scroll"),f(r(a,"scroll",u)),v(c),f("register  1END Scroll")):f("banner not present Scroll")}catch(d){f("detect tree check")}}function D(){a.setTimeout(function(){f("start 1.44");try{$("cookieChoiceInfo").fadeIn(1E3)}catch(a){f("jquery not found")}try{b.getElementById("cookieChoiceInfo").style.opacity=1}catch(a){}},2E3)}function u(c){if(null!=b.getElementById("cookieChoiceInfo")){f("register 1.43");
var d=0;try{for(var e=c.target;e;){if(e.id&&("cookieChoiceDismiss2"==e.id||"cookieChoiceDismiss"==e.id)){d=1;f("found OK or x");break}else if(e.id&&"cookieChoiceInfo"==e.id){f("found cookieConsentId");d=1;break}e=e.parentNode}}catch(g){f("detect tree check")}0==d&&t("optin_click");try{if(0==d)for(var n=c.target;n;){if(n.href&&""!==n.href){f("href event "+n.href);c.preventDefault();break}else f("rec else:"+n);n=n.parentNode}}catch(g){f("errr evnet listener")}f(r(a,"click",u));0==d&&v(c);f("register END ")}else f("banner not present")}
function v(a){a.stopPropagation?a.stopPropagation():a.returnValue=!1}function E(a){v(a)}function w(){if(null!=b.getElementById("cookieChoiceInfo")){var a=b.getElementById("cookieChoiceInfo");a.parentNode.removeChild(a)}}function F(){if(null==x("policy_cookie"))return!0;var a=x("policy_cookie").split("_")[0],c=a.charAt(1),e=a.charAt(2);if(a.length!=G.length){if("1"==c||"1"==e)return f(c+","+e),!1;a=iolcookcs.policyCookieName;c=new Date;c.setTime(c.getTime()+-864E5);c="; expires="+c.toGMTString();b.cookie=
a+"="+c+"; path=/";return!0}return!1}function x(a){a+="=";for(var c=b.cookie.split(";"),e=0;e<c.length;e++){for(var d=c[e];" "==d.charAt(0);)d=d.substring(1,d.length);if(0==d.indexOf(a))return d.substring(a.length,d.length)}return null}var G="DataRecs geo vlocal Advertising tmp1 tmp2 af".split(" "),B=("https:"==b.location.protocol?"https:":"http:")+"//privacy.italiaonline.it/common/cookie/api/set_policy_cookie.php";return{displayCookieBanner:function(){if(F())try{w();var d;if(iol&&iol.overload)f("oveloading tooltip"),
d=iol.overload._createHeaderElement("cookieChoiceInfo","cookieChoiceDismiss","cookieChoiceDismiss2","http://privacy.italiaonline.it/common/cookie/privacy_detail.php?from=banner","leggiLinkIdp");else{f("base tooltip");var l=b.createElement("div");l.id="cookieChoiceInfo";l.style.cssText="opacity:0; text-align:left; font-family: Arial,Helvetica,sans-serif; position: fixed; z-index: 100000000; background: none repeat scroll 0% 0% rgb(22, 121, 195); padding: 5px 25px; line-height: 14px; font-size:14px;  left: 0px; top: 0px; color:#fff;margin: 10px 20px;";
var e=b.createElement("div");e.style.cssText="margin: px 01px";e.appendChild(m("cookieChoiceDismiss","X","vertical-align: middle; color: rgb(255, 255, 255); font-weight: bold; font-family: Tahoma,Geneva,sans-serif; font-size: 15px; text-decoration: none; position:absolute; right:7px; top:5px"));e.appendChild(p("Questo sito utilizza cookie anche di terzi per inviarti pubblicita' e servizi in linea con le tue preferenze. Se vuoi saperne di piu' o negare il consenso a tutti o ad alcuni cookie, ","vertical-align:middle;color: rgb(255, 255, 255);"));
e.appendChild(h("leggiLinkIdp","leggi qui","http://privacy.italiaonline.it/common/cookie/privacy_detail.php?from=banner","vertical-align:middle;color:#FFF; font-weight:bold; text-decoration:none"));e.appendChild(p(". Chiudendo questo banner, scorrendo questa pagina o cliccando qualunque elemento acconsenti all'uso dei cookie.","vertical-align:middle;color: rgb(255, 255, 255);"));e.appendChild(m("cookieChoiceDismiss2","OK","vertical-align: middle; color: rgb(22, 121, 195); font-weight: bold; background: none repeat scroll 0% 0% rgb(238, 238, 238); text-decoration: none; display: inline-block; padding:1px 10px; line-height: 16px; margin: 2px 0px 0px 10px;"));
l.appendChild(e);c("optin_viewtoolbar");d=l}var k=b.createDocumentFragment();k.appendChild(d);b.body.appendChild(k.cloneNode(!0));b.getElementById("cookieChoiceDismiss").onclick=A;b.getElementById("cookieChoiceDismiss2").onclick=z;b.getElementById("leggiLinkIdp").onclick=y;q(a,"click",u);q(a,"scroll",C);D();q("cookieChoiceInfo","click",E)}catch(r){f("showBar problem ")}}}}();a.iolp={cookieChoices:c};return c})(this);iolp.cookieChoices.displayCookieBanner();window.setTimeout(function(){try{iol.dmp2.semtrack()}catch(a){iol.dmp2.log("semtrackAsync")}},
6E3)});iol.iolcookcs.trackCookie=function(a){try{var b=("https:"==document.location.protocol?"https:":"http:")+"//privacy.italiaonline.it/common/cookie/api/set_policy_cookie.php?trvalue="+a+"&r="+Math.floor(10*Math.random()+1),d=document.createElement("IFRAME");d.setAttribute("src",b);d.style.width="0px";d.style.height="0px";d.style.display="none";window.setTimeout(function(){document.body.appendChild(d)},3E3)}catch(c){}};
iol.iolcookcs.isCookieEnable=function(a){for(var b="DataRecs geo vlocal Advertising tmp1 tmp2 af".split(" "),d="0",d="",c=document.cookie.split(";"),g=0;g<c.length;g++){for(var k=c[g];" "==k.charAt(0);)k=k.substring(1,k.length);0==k.indexOf("policy_cookie=")&&(d=k.substring(14,k.length))}if(null!=d&&""!=d){d=d.split("_")[0];c=null;for(index=0;index<b.length;++index)if(b[index]==a){c=index;break}d=null!=c?d.charAt(c):null}else return!0;return"1"==d?!0:!1};
iol.dmp2.semtrackAsync=function(a){try{var b=iol.dmp2.detectbcp();if("undefined"!=typeof a.stes){if("string"==typeof a.stes.tag)b.add("genp","sem:"+a.stes.tag),iol.dmp2.log(a.stes.tag);else for(var d=0;d<a.stes.tag.length;d++)b.add("genp","sem:"+a.stes.tag[d]),iol.dmp2.log(a.stes.tag[d]);b.bcp()}else iol.dmp2.log("nessun val")}catch(c){iol.dmp2.log("semtrackAsync")}};
iol.dmp2.semtrack=function(){try{iol.dmp2.log("Start semtrack "+document.location.href.length),"undefined"!=typeof iol.dmp2.detectbcp()?35<document.location.href.length&&(iol.dmp2.log("url OK"),iol.dmp2.getSemInfo()):iol.dmp2.log("sem stop bcp nt")}catch(a){iol.dmp2.log("semtrack")}};
iol.dmp2.detectbcp=function(){var a;"undefined"!=typeof _cc6200?a=_cc6200:"undefined"!=typeof _cc6206?a=_cc6206:"undefined"!=typeof _cc6202?a=_cc6202:"undefined"!=typeof _cc6205?a=_cc6205:"undefined"!=typeof _cc6207?a=_cc6207:"undefined"!=typeof _cc6204?a=_cc6204:"undefined"!=typeof _cc6233?a=_cc6233:"undefined"!=typeof _cc6328?a=_cc6328:"undefined"!=typeof _cc6775?a=_cc6775:"undefined"!=typeof _cc6235?a=_cc6235:"undefined"!=typeof _cc6367?a=_cc6367:"undefined"!=typeof _cc6232?a=_cc6232:"undefined"!=
typeof _cc6348?a=_cc6348:iol.dmp2.log("bcp non trovato");return a};iol.dmp2.getSemUrl=function(){try{var a=document.location.href;-1<a.indexOf("?")&&(a=a.substring(0,a.indexOf("?")));iol.dmp2.log("clean "+a);return"http://tuttosu.virgilio.it/all-about-api/tags_service_tutto_su.php?id="+encodeURIComponent(a)+"&format=jsonp&callback=iol.dmp2.semtrackAsync"}catch(b){}};iol.dmp2.log=function(a){try{0<document.location.href.indexOf("log=true")&&console.log(a)}catch(b){}};
iol.dmp2.getSemInfo=function(){try{var a=this.getSemUrl(),b=document.createElement("script");b.type="text/javascript";b.src=a;window.setTimeout(function(){try{document.body.appendChild(b)}catch(a){}},3E3)}catch(d){iol.dmp2.log("getSemInfo")}};iol.track.regTracking=function(){try{iol.dmp2.log("start timeout track"),35<document.location.href.length?window.setTimeout(function(){try{iol.track.Tracking()}catch(a){}},3E3):iol.dmp2.log("no track")}catch(a){iol.dmp2.log("regTracking")}};
iol.track.Tracking=function(){try{iol.dmp2.log("track ");var a=window.location.href,b=document.referrer;-1<a.indexOf("?")&&(a=a.substring(0,a.indexOf("?")));var d="";iol.dmp2.log("track referer "+b);iol.dmp2.log("track url "+a);if(-1!=b.indexOf("google.")||-1!=b.indexOf("bing.")){iol.dmp2.log("track seo ");var c="",g=b.indexOf("&q=");-1==g&&(g=b.indexOf("?q="));iol.dmp2.log("track seo 2 "+g);if(-1!=g)var k=b.indexOf("&",g+1),c=b.substring(g+1,k)+"&",c=c.replace("q=","q=seo_");iol.dmp2.log("track seo 3 "+
c);var p=b.indexOf("http://"),m=b.indexOf("/",7);-1==p&&(p=b.indexOf("https://"),m=b.indexOf("/",8),-1==m&&(m=b.length),iol.dmp2.log("track seo 3 https "+p+", "+m));var h=b.substring(0,m).replace("http://","").replace("https://","");try{-1!=h.indexOf("http")&&(h=10<h.length?"f"+h.substring(0,9):"f"+h)}catch(f){}""==c&&(c="q="+h+"&");d=c+"d="+h;iol.dmp2.log("track seo 4 "+d)}else if(b.indexOf("facebook.")||b.indexOf("twitter.")){iol.dmp2.log("track social ");p=b.indexOf("http://");m=b.indexOf("/",
7);-1==p&&(b.indexOf("https://"),m=b.indexOf("/",8));h=b.substring(0,m).replace("http://","").replace("https://","");try{-1!=h.indexOf("http")&&(h=10<h.length?"f"+h.substring(0,9):"f"+h)}catch(f){}d="q="+h+"&d="+h}g=c="";-1!=a.indexOf("dilei.it")?g="IVD_":-1!=a.indexOf("motorlife.it")?g="IVM_":-1!=a.indexOf("quifinanza.it")?g="IVF_":-1!=a.indexOf("siviaggia.it")?g="IVV_":-1!=a.indexOf("sportstadio.it")?g="IWN_":iol.dmp2.log("no dominio track");if(g)if(-1!=a.indexOf("/attachment/"))var q=a.indexOf("/attachment/"),
c=a.substring(a.lastIndexOf("/",q-1)+1,q).replace("/","");else c=a.substring(a.lastIndexOf("/",a.length-2)+1).replace("/","");q=/^\d+$/;""==c||q.test(c)?c=g+c:(iol.dmp2.log("ID not detected"),c="");if(""!=c&&""!=b){var r=document.createElement("img");r.type="text/javascript";r.src="http://kpi.plug.it/tracks/bi/images/RT_A.gif?link="+a+"&"+d+"&id=C_"+c+"&rand="+Math.floor(1E7*Math.random()+1);iol.dmp2.log("track url.src "+r.src);document.body.appendChild(r)}}catch(f){iol.dmp2.log("Tracking")}};iol.track.regTracking();
