#!/bin/sh
set -x

Parameter_num=$#
Parameter_one=$1
PathNow=`dirname $0`
AppPath="/opt/app"
LastValue=
IpkName="welcome*.ipk"
CgiBin="p5g6"
LanIP=`uci get network.lan.ipaddr`

#判断参数是否合法
FunParamLegal()
{
	if [ ${Parameter_num} -ne 1 ];then
		echo "Fail:Parameter Err."
		exit 1
	fi
}

#查看进程号
CheckProgressNum()
{
	local L_NumProgress=`ps | grep uhttp | grep welcome | awk -F " " '{print $1}'`
	echo ${L_NumProgress}
}

#增加NAT防火墙基本规则
FirewallInit()
{
	iptables -t nat -I PREROUTING -i br-lan -p tcp -s ${LanIP}/24 --dport 80 -j DNAT --to ${LanIP}:88
	iptables -t nat -I PREROUTING -i br-lan -p tcp -s ${LanIP}/24 -d ${LanIP}/32 -j ACCEPT
	
}

#删除NAT防火墙基本规则
FirewallClear()
{
	iptables -t nat -D PREROUTING -i br-lan -p tcp -s ${LanIP}/24 --dport 80 -j DNAT --to ${LanIP}:88
}

#开启WEB监听
UhttpdStart()
{
	/usr/sbin/uhttpd -f -h /www/welcome -r xRouter -x /${CgiBin} -E /${CgiBin}/luci/welcome -n 3 -p 0.0.0.0:88 &
}


#安装函数
Install()
{
	local L_ExitStatus=0

	cd ${PathNow}
	
	if [ ! -d "${AppPath}" ];then
		mkdir -p ${AppPath}
	fi
	
	if [ -f ${IpkName} ];then
		tar xzvf ${IpkName} -C ${AppPath}
		LastValue=$?
	else
		echo "Fail:Install file is not exist."
		L_ExitStatus=1
	fi
	if [ ${LastValue} -eq 0 ];then
		mkdir -p /www/welcome/${CgiBin}
		ln -s /www/cgi-bin/luci /www/welcome/${CgiBin}/luci
		ln -s ${AppPath}/welcome/script /usr/lib/lua/luci/controller/welcome
		ln -s ${AppPath}/welcome/html /usr/lib/lua/luci/view/welcome
		
		rm -fr /tmp/luci-*
		echo "Success."
		L_ExitStatus=0
	else
		echo "Fail:Install Err."
		L_ExitStatus=2
	fi
	cd -
	exit ${L_ExitStatus}
}

#卸载函数
unInstall()
{
	local L_ExitStatus=0
	local L_NumProgress=""
	
	L_NumProgress=`CheckProgressNum`
	if [ "${L_NumProgress}" != "" ];then
		kill -9 ${L_NumProgress}
	fi	
	
	cd ${PathNow}
		rm  -fr ../welcome
	cd -
	
	rm -fr /usr/lib/lua/luci/controller/welcome
	rm -fr /usr/lib/lua/luci/view/welcome
	rm -fr /www/welcome

	FirewallClear

	echo "Success."
	exit ${L_ExitStatus}
}

#启动函数
Start()
{
	local L_ExitStatus=0
	
	UhttpdStart

	FirewallInit

	LastValue=$?
	if [ ${LastValue} -eq 0 ];then
		echo "Success."
		L_ExitStatus=0
	else
		echo "Fail:Start Err."
		L_ExitStatus=1
	fi
	
	cd -	

	exit ${L_ExitStatus}	
}

#停止函数
Stop()
{
	local L_ExitStatus=0
	local L_NumProgress=""
	
	FirewallClear
	
	L_NumProgress=`CheckProgressNum`
	if [ "${L_NumProgress}" != "" ];then
		kill -9 ${L_NumProgress}
		LastValue=$?
		if [ ${LastValue} -eq 0 ];then
			echo "Success."
		else
			echo "Fail:Stop Err."
			L_ExitStatus=1
		fi
	else
		echo "Success."
		L_ExitStatus=0		
	fi
		
	exit ${L_ExitStatus}	
}


#重新启动函数
Restart()
{
	local L_ExitStatus=0
	local L_NumProgress=""
	
	L_NumProgress=`CheckProgressNum`
	if [ "${L_NumProgress}" != "" ];then
		kill -9 ${L_NumProgress}
	fi
	
	UhttpdStart
	
	FirewallClear
	
	FirewallInit
	
	LastValue=$?
	if [ ${LastValue} -eq 0 ];then
		echo "Success."
		L_ExitStatus=0
	else
		echo "Fail:Start Err."
		L_ExitStatus=1
	fi
	
	cd -	
	exit ${L_ExitStatus}	
}

#查看运行状态函数
CheckRunStatus()
{
	local L_ExitStatus=0
	local L_NumProgress=""
	
	#查看程序运行状态
	L_NumProgress=`CheckProgressNum`
	if [ "${L_NumProgress}" != "" ];then
		local L_FirewallRule=`iptables -t nat -L PREROUTING|grep ":88"|wc -l`
		if [ ${L_FirewallRule} -eq 1 ];then
			echo "Success."
			L_ExitStatus=0
		else
			echo "Fail:Start Err."
			L_ExitStatus=2
		fi
	else
		echo "Fail."
		L_ExitStatus=1		
	fi	

	exit ${L_ExitStatus}
}

#主函数
Main()
{
	#安装
	if [ "${Parameter_one}" = "install" ];then
		Install
	
	#卸载
	elif [ "${Parameter_one}" = "uninstall" ];then
		unInstall
	
	#启动
	elif [ "${Parameter_one}" = "start" ];then
		Start
	
	#停止
	elif [ "${Parameter_one}" = "stop" ];then
		Stop	
	
	#重启
	elif [ "${Parameter_one}" = "restart" ];then
		Restart
		
	#查看运行状态
	elif [ "${Parameter_one}" = "runstatus" ];then
		CheckRunStatus
		
	#输入参数错误
	else
		echo "ERR:Parameter Err."
		exit 1	
	fi
}

#检查参数是否合法
FunParamLegal

#执行主函数
Main
